#!/bin/sh
set -e

# Check environment

fail() {
    echo "$1" >&2
    echo "Usage: $(basename "$0") [USER] [PASSWORD]" >&2
    exit 1
}

if [ -z "${PAM_PWDFILE}" ] ; then
    fail "Environment variable \"PAM_PWDFILE\" is missing."
fi

if [ -z "$1" ] ; then
    fail "Argument \"USER\" is missing."
fi

if [ -z "$2" ] ; then
    fail "Argument \"PASSWORD\" is missing."
fi

# Add user

htpasswd -b -d "${PAM_PWDFILE}" "$1" "$2"
