#!/bin/sh
set -e

# Check environment

fail() {
    echo "$1" >&2
    echo "Usage: $(basename "$0") [USER]" >&2
    exit 1
}

if [ -z "${PAM_PWDFILE}" ] ; then
    fail "Environment variable \"PAM_PWDFILE\" is missing."
fi

if [ -z "$1" ] ; then
    fail "Argument \"USER\" is missing."
fi

# Remove user

sed --in-place "/^$1:/ d" "${PAM_PWDFILE}"
