#!/bin/bash
set -e

for OPTION in $(env | grep "VSFTPD_OPTION_*") ; do
    KEY=$(echo "${OPTION:14}" | cut --delimiter = --fields 1 | tr "[:upper:]" "[:lower:]")
    VALUE=$(echo "${OPTION}" | cut --delimiter = --fields 2)
    echo "${KEY}=${VALUE}" >> /etc/vsftpd/vsftpd.conf
done
