#!/bin/sh
set -e

fail() {
    echo $1 >&2
    echo "usage: $0 [USER] [PASSWORD]" >&2
    exit 1
}

[[ -z $PWD_FILE ]] && fail "Environment variable PWD_FILE is missing."
[[ -z $1 ]] && fail "Argument USER is missing."
[[ -z $2 ]] && fail "Argument PASSWORD is missing."

[[ ! -f $PWD_FILE ]] && touch $PWD_FILE
htpasswd -db $PWD_FILE $1 $2
